vim.keymap.set("n", "<Leader>pm", ":PhpactorContextMenu<CR>")
vim.keymap.set("n", "<Leader>pn", ":PhpactorClassNew<CR>")
vim.keymap.set("n", "<Leader>pi", ":PhpactorImportClass<CR>", { silent = true })
vim.keymap.set("n", "<Leader>pe", ":PhpactorClassExpand<CR>")
vim.keymap.set("n", "<Leader>ph", ":PhpactorHover<CR>")
